#!/bin/bash

java -classpath .:lib/antlr-runtime-3.1.3.jar:lib/commons-io-1.4.jar:lib/jppf-client.jar:lib/log4j-1.2.16.jar:lib/xpp3_min-1.1.4c.jar:lib/cmaes_java.jar:lib/commons-lang-2.5.jar:lib/jppf-common-node.jar:lib/phys2d-251007.jar:lib/xstream-1.3.1.jar:lib/commons-collections-3.2.1.jar:lib/commons-logging-1.1.1.jar:lib/jppf-common.jar:lib/slf4j-api-1.5.2.jar:lib/commons-configuration-1.6.jar:lib/jcl-over-slf4j-1.5.2.jar:lib/log4j-1.2.15.jar:lib/slf4j-log4j12-1.5.2.jar gpat.demo.GPATMain exp"$1"/cfg.properties exp"$1" >>out.log 2>>err.log 
