#!/bin/bash

if [ $# != 2 ] ; then
    echo "usage: "$0" BASE_ALGORITHM NAME"
    exit
fi

BALG="${1}"
NAME="${2}"
CPUS="${3}"
NEDIR="/Users/drchaj1/java/ne"

case ${BALG} in
	"GP")
    	export CLASS="common.run.Runner"
		export CFG=${NEDIR}"/cfg/demo/gpdemo.properties"
		;;
	"GPAT")
    	export CLASS="common.run.Runner"
		export CFG=${NEDIR}"/cfg/demo/gpatdemo.properties"
		;;
	"GPATS")
    	export CLASS="common.run.Runner"
		export CFG=${NEDIR}"/cfg/demo/gpatsimpledemo.properties"
		;;
	"NEAT")
    	export CLASS="common.run.Runner"
		export CFG=${NEDIR}"/cfg/demo/neatdemo.properties"
		;;		
	"HGP")
    	export CLASS="hyper.experiments.HyperRunner"
		export CFG=${NEDIR}"/cfg/hyper/gphyper.properties"
		;;
	"HGPAT")
    	export CLASS="hyper.experiments.HyperRunner"
		export CFG=${NEDIR}"/cfg/hyper/gpathyper.properties"
		;;
	"HNEAT")
    	export CLASS="hyper.experiments.HyperRunner"
		export CFG=${NEDIR}"/cfg/hyper/neathyper.properties"
		;;
	*)
		echo "Unknown BASE ALGORITHM: "${BALG}" !!!"
		exit 1 ;;
esac

# par. 1: machine and dir to run
# par. 2: problem config file dir
# par. 3: problem config file name (no extension)
# par. 4: number of CPUs
function run {
    sed -i "" "1s/.*/INCLUDE = "${2}"\/"${3}"\.properties/" ${CFG}
    sed -i "" "s/^PARALLEL\.FORCE_THREADS.*/PARALLEL\.FORCE_THREADS = "${4}"/" ${CFG}
    ./nepackage ${BALG} ${NAME}"_"${3}
    ./runssh ${1}
}

#echo "CHECK"
#echo "	- The project has actual BUILD."
#echo "	- All problem includes are COMMENTED OUT."
#read -n 1 -p "Press any key to continue..."

if [[ ${BALG} == H* ]]
then
	echo "INDIRECT ENCODING EXPERIMENTS"
	run "drchal:~/scratch/nepack"${BALG}"_"${NAME}"_rcM" "reco" "rcM" 4
	run "kovarik:~/scratch/nepack"${BALG}"_"${NAME}"_rcS" "reco" "rcS" 4
	run "brian:~/scratch/nepack"${BALG}"_"${NAME}"_rcR" "reco" "rcR" 4
	
	run "brian:~/scratch/nepack"${BALG}"_"${NAME}"_xor" "bool" "xor" 5
	
	run "pilny:~/scratch/nepack"${BALG}"_"${NAME}"_fc55" "fc" "fc55" 4

else
	echo "DIRECT ENCODING EXPERIMENTS"

	run "drchal:~/scratch/nepack"${BALG}"_"${NAME}"_1DF" "regression" "1DF" 3
	run "brian:~/scratch/nepack"${BALG}"_"${NAME}"_1DH" "regression" "1DH" 3
	
	run "drchal:~/scratch/nepack"${BALG}"_"${NAME}"_2DI" "regression" "2DI" 3
	run "drchal:~/scratch/nepack"${BALG}"_"${NAME}"_2DK" "regression" "2DK" 3
	
	run "brian:~/scratch/nepack"${BALG}"_"${NAME}"_3DE" "regression" "3DE" 3
	run "pilny:~/scratch/nepack"${BALG}"_"${NAME}"_3DH" "regression" "3DH" 3
	run "kovarik:~/scratch/nepack"${BALG}"_"${NAME}"_3DK" "regression" "3DK" 3
	
	run "brian:~/scratch/nepack"${BALG}"_"${NAME}"_4DC" "regression" "4DC" 3
	run "pilny:~/scratch/nepack"${BALG}"_"${NAME}"_4DF" "regression" "4DF" 3
	run "kovarik:~/scratch/nepack"${BALG}"_"${NAME}"_4DG" "regression" "4DG" 3
	run "brian:~/scratch/nepack"${BALG}"_"${NAME}"_4DV" "regression" "4DV" 3
	
	run "pilny:~/scratch/nepack"${BALG}"_"${NAME}"_M1" "maze" "M1" 3
	run "kovarik:~/scratch/nepack"${BALG}"_"${NAME}"_M2" "maze" "M2" 3
fi
