#!/bin/bash

if [ $# != 2 ] ; then
    echo "usage: "$0"  PREFIX NAME"
    exit
fi

PREFIX="${1}"
NAME="${2}"
NEDIR=~/java/ne
CFG=${NEDIR}/cfg/hyper/gpathyper.properties


function run {
    sed -i "" "1s/.*/INCLUDE = "${3}"\/"${4}"\.properties/" ${CFG}
    ./nepackage ${1} ${PREFIX}"_"${4}_${NAME}
    ./runssh ${2}
}

run "HGPAT" "kovarik:~/nepackh4" "bool" "xor"
run "HGPAT" "drchal:~/nepackh5" "reco" "reco1D"
run "HGPAT" "kovarik:~/nepackh6" "fc" "fc55"
