#!/bin/bash

if [ $# -ne 1 ] ; then
    echo "usage: "$0" prefix"
    exit 1
fi

./collect ${1} ${1}"_1DF" ${1}"_1DH" ${1}"_2DI" ${1}"_2DK" ${1}"_3DE" ${1}"_3DH" ${1}"_3DK" ${1}"_4DC" ${1}"_4DF" ${1}"_4DG" ${1}"_4DV" ${1}"_M1" ${1}"_M2"
