#!/bin/bash

#USAGE:
#nepackage algorithm expdir copyback
# algorithms: GP, GPAT 
export NEDIR=~/java/ne
export NEPACKAGE=nepack
export ARCHIVE=/tmp/nepack.tar.gz
export RUNSCRIPT=${NEPACKAGE}/run
export INFOSCRIPT=${NEPACKAGE}/info
export NAMEFILE=${NEPACKAGE}/name

export EXPDIR=exp
export CLASS="common.run.Runner"
export CFG="cfg/demo/gpatdemo.properties"

if [ $# -ge 1 ] ; then
    if [ "${1}" == "GP" ] ; then
        export CLASS="common.run.Runner"
	export CFG="cfg/demo/gpdemo.properties"
    fi
    if [ "${1}" == "GPAT" ] ; then
        export CLASS="common.run.Runner"
	export CFG="cfg/demo/gpatdemo.properties"
    fi
    if [ "${1}" == "GPATS" ] ; then
        export CLASS="common.run.Runner"
	export CFG="cfg/demo/gpatsimpledemo.properties"
    fi
    if [ "${1}" == "NEAT" ] ; then
        export CLASS="common.run.Runner"
	export CFG="cfg/demo/neatdemo.properties"
    fi
    if [ "${1}" == "HGP" ] ; then
        export CLASS="hyper.experiments.HyperRunner"
	export CFG="cfg/hyper/gphyper.properties"
    fi
    if [ "${1}" == "HGPAT" ] ; then
        export CLASS="hyper.experiments.HyperRunner"
	export CFG="cfg/hyper/gpathyper.properties"
    fi
    if [ "${1}" == "HNEAT" ] ; then
        export CLASS="hyper.experiments.HyperRunner"
	export CFG="cfg/hyper/neathyper.properties"
    fi

fi
if [ $# -ge 2 ] ; then
    export EXPDIR="${2}"
fi
if [ $# -ge 3 ] ; then
    export COPYBACK="${3}"
fi

cd /tmp

rm -rf ${NEPACKAGE}
mkdir ${NEPACKAGE}

cp -r ${NEDIR}/out/production/Ne/ ${NEPACKAGE}/
#Vivae
cp -r ${NEDIR}/out/production/Vivae/ ${NEPACKAGE}/

#mkdir ${NEPACKAGE}/lib
mkdir ${NEPACKAGE}/${EXPDIR}

#find ${NEDIR}/ne/lib -type f -exec cp {} ${NEPACKAGE}/lib/ \;
#Vivae
#find ${NEDIR}/vivae/vivae/lib -type f -exec cp {} ${NEPACKAGE}/lib/ \;

cp -r ${NEDIR}/ne/cfg ${NEPACKAGE}
#Vivae
cp -r ${NEDIR}/vivae/vivae/cfg ${NEPACKAGE}

echo '#!/bin/bash' > ${RUNSCRIPT}
chmod a+x ${RUNSCRIPT}
echo 'source ~/environment' >> ${RUNSCRIPT}
echo 'ln -s ~/nelib ./lib' >> ${RUNSCRIPT}

echo 'export CLASS="'${CLASS}'"' >> ${RUNSCRIPT}
echo 'export CFG="'${CFG}'"' >> ${RUNSCRIPT}

export CP='export CLASSPATH=."'
for f in ${NEPACKAGE}/lib/*
do
    CP=${CP}':lib/'`basename ${f}`
done

CP=${CP}'"'

echo ${CP} >> ${RUNSCRIPT}

echo 'hostname > '${EXPDIR}'/_host_.txt'  >> ${RUNSCRIPT}
echo 'free -m >> '${EXPDIR}'/_host_.txt'  >> ${RUNSCRIPT}
echo 'cat /proc/cpuinfo >> '${EXPDIR}'/_host_.txt'  >> ${RUNSCRIPT}

echo 'java -Xmx2048M -classpath ${CLASSPATH} ${CLASS} ${CFG} '${EXPDIR}' >>out.log 2>>err.log' >> ${RUNSCRIPT}

if [ -n "${COPYBACK}" ] ; then
    echo 'scp -r '${EXPDIR}' '${COPYBACK}':' >> ${RUNSCRIPT}
fi

echo '#!/bin/bash' > ${INFOSCRIPT}
chmod a+x ${INFOSCRIPT}
echo 'export EXPDIR="'${EXPDIR}'"' >> ${INFOSCRIPT}
echo 'cd ${EXPDIR}' >> ${INFOSCRIPT}
echo 'if [ -e "experiments_overall.txt" ] ; then' >> ${INFOSCRIPT}
echo 'echo "FINISHED "${EXPDIR}' >> ${INFOSCRIPT}
echo 'exit' >> ${INFOSCRIPT}
echo 'fi' >> ${INFOSCRIPT}
echo 'export CONFIG=`ls parameters_???.txt | tr " " "\n" | tail -n1 | sed "s/parameters\_\(.*\)\.txt/\1/"`' >> ${INFOSCRIPT}
echo 'export EXP=`cat _experiment_id.txt`' >> ${INFOSCRIPT}
echo 'echo ${CONFIG}" "${EXP}" "${EXPDIR}' >> ${INFOSCRIPT}

echo ${EXPDIR} > ${NAMEFILE}

tar czf ${ARCHIVE} ${NEPACKAGE}
